# Generated by Django 5.0 on 2023-12-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_no_of_guests_alter_menu_inventory'),
        ('restaurant', '0004_alter_booking_no_of_guests'),
    ]

    operations = [
    ]
